---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kserve-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kserve-selfsigned-ca
  namespace: cert-manager
spec:
  secretName: kserve-ca
  isCA: true
  commonName: selfsigned-ca
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: kserve-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kserve-ca-issuer
spec:
  ca:
    secretName: kserve-ca