varReference:
  - path: spec/template/spec/containers/image
    kind: Deployment
  - path: data
    kind: ConfigMap
  - path: spec/router/scheduler/template/containers/image
    kind: LLMInferenceServiceConfig
  - path: spec/worker/initContainers/image
    kind: LLMInferenceServiceConfig
  - path: spec/template/initContainers/image
    kind: LLMInferenceServiceConfig
  - path: spec/commonName
    kind: Certificate
  - path: spec/dnsNames
    kind: Certificate
  - path: metadata/annotations/cert-manager.io\/inject-ca-from
    kind: ValidatingWebhookConfiguration
  - path: metadata/annotations/cert-manager.io\/inject-ca-from
    kind: MutatingWebhookConfiguration