apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: servingruntime.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: kserve/serving-cert
webhooks:
  - name: servingruntime.kserve-webhook-server.validator
