apiVersion: dscinitialization.opendatahub.io/v2
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  monitoring:
    managementState: "Removed"
    namespace: 'opendatahub'
    metrics: {}
  applicationsNamespace: 'opendatahub'
  trustedCABundle:
    managementState: "Removed"
    customCABundle: ""

