apiVersion: v2
name: opendatahub-operator-chart
description: A Helm chart for Open Data Hub Operator on vanilla Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "vanilla"

keywords:
  - opendatahub
  - ai
  - ml
  - operator
  - kubernetes

maintainers:
  - name: OpenDataHub Community
