apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    opendatahub.io/namespace: "true"
  name: {{ .Values.components.namespace }}
