---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/opendatahub-operator-serving-cert
  name: opendatahub-operator-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-datasciencecluster-v1
  failurePolicy: Fail
  matchPolicy: Exact
  name: datasciencecluster-v1-defaulter.opendatahub.io
  rules:
  - apiGroups:
    - datasciencecluster.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - datascienceclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-datasciencecluster-v2
  failurePolicy: Fail
  matchPolicy: Exact
  name: datasciencecluster-v2-defaulter.opendatahub.io
  rules:
  - apiGroups:
    - datasciencecluster.opendatahub.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - datascienceclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-hardware-profile
  failurePolicy: Fail
  name: hardwareprofile-isvc-injector.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferenceservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-hardware-profile
  failurePolicy: Fail
  name: hardwareprofile-llmisvc-injector.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llminferenceservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-hardware-profile
  failurePolicy: Fail
  name: hardwareprofile-notebook-injector.opendatahub.io
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /platform-connection-notebook
  failurePolicy: Fail
  name: connection-notebook.opendatahub.io
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /platform-connection-isvc
  failurePolicy: Fail
  name: connection-isvc.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferenceservices
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /platform-connection-llmisvc
  failurePolicy: Fail
  name: connection-llmisvc.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llminferenceservices
  sideEffects: NoneOnDryRun
