---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/opendatahub-operator-serving-cert
  name: opendatahub-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-dashboard-acceleratorprofile
  failurePolicy: Fail
  name: dashboard-acceleratorprofile-validator.opendatahub.io
  rules:
  - apiGroups:
    - dashboard.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - acceleratorprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-dashboard-hardwareprofile
  failurePolicy: Fail
  name: dashboard-hardwareprofile-validator.opendatahub.io
  rules:
  - apiGroups:
    - dashboard.opendatahub.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hardwareprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-datasciencecluster-v1
  failurePolicy: Fail
  matchPolicy: Exact
  name: datasciencecluster-v1-validator.opendatahub.io
  rules:
  - apiGroups:
    - datasciencecluster.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - datascienceclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-datasciencecluster-v2
  failurePolicy: Fail
  matchPolicy: Exact
  name: datasciencecluster-v2-validator.opendatahub.io
  rules:
  - apiGroups:
    - datasciencecluster.opendatahub.io
    apiVersions:
    - v2
    operations:
    - CREATE
    resources:
    - datascienceclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-dscinitialization-v1
  failurePolicy: Fail
  matchPolicy: Exact
  name: dscinitialization-v1-validator.opendatahub.io
  rules:
  - apiGroups:
    - dscinitialization.opendatahub.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - DELETE
    resources:
    - dscinitializations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-dscinitialization-v2
  failurePolicy: Fail
  matchPolicy: Exact
  name: dscinitialization-v2-validator.opendatahub.io
  rules:
  - apiGroups:
    - dscinitialization.opendatahub.io
    apiVersions:
    - v2
    operations:
    - CREATE
    - DELETE
    resources:
    - dscinitializations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-kueue
  failurePolicy: Fail
  name: kserve-isvc-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inferenceservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-kueue
  failurePolicy: Fail
  name: kserve-llmisvc-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - llminferenceservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-kueue
  failurePolicy: Fail
  name: kubeflow-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pytorchjobs
    - notebooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: opendatahub-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-kueue
  failurePolicy: Fail
  name: ray-kueuelabels-validator.opendatahub.io
  rules:
  - apiGroups:
    - ray.io
    apiVersions:
    - v1
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rayjobs
    - rayclusters
  sideEffects: None
